config/routes.rb
Rails.application.routes.draw do

  get "/", to: "product#index"
  get "/account", to: "product#account", as: :account
  get "/scarves/:id", to: "product#show_one", as: :scarf
  get "/scarves", to: "product#show_all", as: :scarves

  get "/signup", to: "product#signup", as: :signup
  post "/signup", to: "user#create", as: :create

  get "/log-out", to: "sessions#log_out", as: :log_out
  post "/log-in", to: "sessions#log_in", as: :log_in

  get "/cart", to: "item#cart", as: :cart
  post "/scarves/:id", to: "item#add_to_cart", as: :add_to_cart
  post "/cart/:id", to: "item#update_cart"
  delete "/cart/:id", to: "item#delete_item"

  get "/products", to: "admin#index", as: :product_index
  post "/products/admin", to: "admin#add_product"
  get "/product/admin/:id", to: "admin#show_one", as: :product_edit
  post "/product/admin/:id", to: "admin#update"
  delete "/product/admin/:id", to: "admin#delete"

  get "/checkout", to: "order#checkout"

end

app/views/admin/index.html.erb
<!DOCTYPE html>

<h1>Scarves!</h1>

<div class = "form">

  <form action="/products/admin" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <div>
      <h4>
        <label for="name-input">Add a Scarf</label>
      </h4>
      <input type="text" id = "name-input" name="name" />
    </div>
    <div>
      <h4>
        <label for="description-input">Scarf Description</label>
      </h4>
      <input type="text" id = "description-input" name="description" />
    </div>
    <div>
      <h4>
        <label for="image-input">Scarf Image</label>
      </h4>
      <input type="text" id = "image-input" name="image_url" />
    </div>
    <div>
      <h4>
        <label for="type-input">Scarf Type</label>
      </h4>
      <input type="text" id = "type-input" name="type" />
    </div>
    <div>
      <h4>
        <label for="price-input">Scarf Price in Cents</label>
      </h4>
      <input type="text" id = "price-input" name="price_in_cents" />
    </div>
    <div class="submit">
      <input type="submit" class="btn btn-default" />
    </div>
  </form>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% @products.in_groups_of(4, false).each do |group| %>
        <div class="row">
          <% group.each do |product| %>
            <div class="product col-md-3">
              <%= image_tag product.image_url %>
              <h3><%= link_to product.name, product_edit_path(product.id) %></h3>
              <li><%= product.description %></li>
              <li><%= ProductOption.find_by(product_id: product.id).name %></li>
              <li><%= number_to_currency((ProductOption.find_by(product_id: product.id).price_in_cents) * 0.01) %></li>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/show_one.html.erb
<div class="container">

    <h1><%= @product.name %></h1>

  <div class = "form">

    <form action="/product/admin/<%= @product.id %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <div>
        <h4>
          <label for="name-input">EDIT Add a Scarf</label>
        </h4>
        <input type="text" id = "name-input" name="name" value="<%= @product.name %>" />
      </div>
      <div>
        <h4>
          <label for="description-input">EDIT Scarf Description</label>
        </h4>
        <input type="text" id = "description-input" name="description" value="<%= @product.description %>" />
      </div>
      <div>
        <h4>
          <label for="image-input">EDIT Scarf Image</label>
        </h4>
        <input type="text" id = "image-input" name="image_url" value="<%= @product.image_url %>" />
      </div>
      <div>
        <h4>
          <label for="type-input">EDIT Scarf Type</label>
        </h4>
        <input type="text" id = "type-input" name="type" value="<%= @product_option.name %>" />
      </div>
      <div>
        <h4>
          <label for="price-input">EDIT Scarf Price in Cents</label>
        </h4>
        <input type="text" id = "price-input" name="price_in_cents" value="<%= @product_option.price_in_cents %>" />
      </div>
      <div class="update">
        <input type="submit" value="Update" class="btn btn-default" />
      </div>
    </form>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="product_details">
          <li><%= image_tag @product.image_url %></li>
          <li><%= @product.description %></li>
          <li><%= @product_option.name %></li>
          <li><%= number_to_currency((@product_option.price_in_cents) * 0.01) %></li>
        </div>
      </div>
    </div>
  </div>

  <div class="buttons">
    <form action="/product/admin/<%= @product.id %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <input type="hidden" name="_method" value="DELETE" />
      <input type="submit" value="Delete Product" class="btn btn-default" data-confirm="Delete the product?" />
    </form>
  </div>
</div>