config/routes.rb
Rails.application.routes.draw do

  get "/", to: "product#index"
  get "/account", to: "product#account", as: :account
  get "/scarves/:id", to: "product#show_one", as: :scarf
  get "/scarves", to: "product#show_all", as: :scarves

  get "/signup", to: "product#signup", as: :signup
  post "/signup", to: "user#create", as: :create

  get "/log-out", to: "sessions#log_out", as: :log_out
  post "/log-in", to: "sessions#log_in", as: :log_in

  get "/cart", to: "item#cart", as: :cart
  post "/scarves/:id", to: "item#add_to_cart", as: :add_to_cart
  post "/cart/:id", to: "item#update_cart"
  delete "/cart/:id", to: "item#delete_item"

  get "/products", to: "admin#index", as: :product_index
  post "/products/admin", to: "admin#add_product"
  get "/product/admin/:id", to: "admin#show_one", as: :product_edit
  post "/product/admin/:id", to: "admin#update"
  delete "/product/admin/:id", to: "admin#delete"

  get "/checkout", to: "order#checkout"

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_options

  validates :name, presence: true
  validates :description, presence: true
  validates :image_url, presence: true

  validates_associated :product_options

end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  def index

  end

  def account

  end

  def show_all
    @products = Product.all
  end

  # def show_product_opt
  #   @product_option = ProductOption.new
  #   @product_option.name = params[:name]
  #   @product_option.price_in_cents = params[:price_in_cents]
  #   @product_option.product_id = params[:id]
  #   @product_option.save
  # end

  def show_one
    @product = Product.find(params[:id])
    @product_option = ProductOption.find_by(product_id: params[:id])
  end

  # def cart
  #  @items = Item.all
  # end

  def signup

  end

end

app/views/product/account.html.erb
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">Profile</a></li>
      <li><a href="#profile" data-toggle="tab">Password</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="home">
        <form id="tab">
            <label>Email</label>
            <input type="text" value="<%= @current_user.email %>" class="input-xlarge">
            <label>Address</label>
            <textarea value="Smith" rows="3" class="input-xlarge">2817 S 49th
    Apt 314
    San Jose, CA 95101
            </textarea>
          	<div>
        	    <button class="btn btn-primary">Update</button>
        	</div>
        </form>
      </div>
      <div class="tab-pane fade" id="profile">
    	<form id="tab2">
        	<label>New Password</label>
        	<input type="password" class="input-xlarge">
        	<div>
        	    <button class="btn btn-primary">Update</button>
        	</div>
    	</form>
      </div>
  </div>

app/views/product/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div id="this-carousel-id" class="carousel slide">
        <div class="carousel-inner">
          <div class="item active">
            <img src="https://s3-us-west-2.amazonaws.com/scarf.store/rainy_day.jpg" alt="" class="img-responsive center-block" />
            <div class="carousel-caption">
              <p>Scarves for all types of weather.</p>
            </div>
          </div>
          <div class="item">
            <img src="https://s3-us-west-2.amazonaws.com/scarf.store/alki.jpg" alt="" class="img-responsive center-block" />
            <div class="carousel-caption">
              <p>Scarves for all types of weather.</p>
            </div>
          </div>
          <div class="item">
            <img src="https://s3-us-west-2.amazonaws.com/scarf.store/spaceneedle.jpg" alt="" class="img-responsive center-block" />
            <div class="carousel-caption">
              <p>Scarves for all types of weather.</p>
            </div>
          </div>
        </div>
          <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
          <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
      </div>
    </div>

    <!-- <div class="links_container">
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="img_link" >
          <img src="http://placeimg.com/360/300/nature" class="img-responsive" >
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="img_link">
          <img src="http://placeimg.com/360/300/nature" class="img-responsive" >
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="img_link">
          <img src="http://placeimg.com/360/300/nature" class="img-responsive" >
        </div>
      </div>
    </div> -->


  </div>
</div>

app/views/product/show_all.html.erb
<h1>Scarves!</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% @products.in_groups_of(4, false).each do |group| %>
        <div class="row">
          <% group.each do |product| %>
            <div class="product col-md-3">
              <%= image_tag product.image_url %>
              <h3><%= link_to product.name, scarf_path(product.id) %></h3>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>



  <!-- <% @products.each do |product| %>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
      <%= image_tag product.image_url %>
      <li><%= link_to product.name, scarf_path(product.id) %></li>
      <%=product.description %>
    </div>
  <% end %>
  </div>
</div> -->

app/views/product/show_one.html.erb
<h1><%= @product.name %></h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="product_details">
        <%= image_tag @product.image_url %>
        <li><%= @product.description %></li>
        <li><%= @product_option.name %></li>
        <li><%= number_to_currency((@product_option.price_in_cents) * 0.01) %></li>
      </div>
    </div>

    <div class="buttons">
      <form action="/scarves/<%= @product.id %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
        <input type="submit" value="Add to Cart" class="btn btn-default" />
      </form>
    </div>
  </div>
</div>

app/views/product/signup.html.erb
<h1>Sign Up</h1>

  <div class="container">
    <div class="row centered-form">
      <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        <div class="panel panel-default">
        	<div class="panel-heading">
			    	<h3 class="panel-title">Sign Up for Wrap It Up!</h3>
			 		</div>
			 		<div class="panel-body">
			    	<form role="form" action="/signup" method="POST">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
			    		<div class="form-group">
			    			<input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address" value="<%= @email %>">
			  			</div>

		    			<div class="row">
		    				<div class="col-xs-6 col-sm-6 col-md-6">
		    					<div class="form-group">
		    						<input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
		    					</div>
		    				</div>
		    				<div class="col-xs-6 col-sm-6 col-md-6">
		    					<div class="form-group">
		    						<input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-sm" placeholder="Confirm Password">
		    					</div>
		    				</div>
		    			</div>

			    		<input type="submit" value="Sign Up!" class="btn btn-info btn-block">

			    	</form>
			    </div>
	    	</div>
    	</div>
    </div>
  </div>