config/routes.rb
Rails.application.routes.draw do

  get "/", to: "product#index"
  get "/account", to: "product#account", as: :account
  get "/scarves/:id", to: "product#show_one", as: :scarf
  get "/scarves", to: "product#show_all", as: :scarves

  get "/signup", to: "product#signup", as: :signup
  post "/signup", to: "user#create", as: :create

  get "/log-out", to: "sessions#log_out", as: :log_out
  post "/log-in", to: "sessions#log_in", as: :log_in

  get "/cart", to: "item#cart", as: :cart
  post "/scarves/:id", to: "item#add_to_cart", as: :add_to_cart
  post "/cart/:id", to: "item#update_cart"
  delete "/cart/:id", to: "item#delete_item"

  get "/products", to: "admin#index", as: :product_index
  post "/products/admin", to: "admin#add_product"
  get "/product/admin/:id", to: "admin#show_one", as: :product_edit
  post "/product/admin/:id", to: "admin#update"
  delete "/product/admin/:id", to: "admin#delete"

  get "/checkout", to: "order#checkout"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wrap It Up!</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
</head>
<body>

  <% if flash.key?(:notice) %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash.key?(:warning) %>
    <div class="alert alert-danger">
      <%= flash[:warning] %>
    </div>
  <% end %>

  <% if flash.key?(:success) %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Wrap It Up!", "/", class: "navbar-brand" %>
        <button class="navbar-toggle collapsed" data-toggle="collapse" data-target=".menu_bar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="menu_bar collapse navbar-collapse">
        <div class="navbar-right">
          <ul class="nav navbar-nav">
            <% cart_total = 0 %>
            <% Item.all.each do |item| %>
              <% cart_total += item.quantity %>
            <% end %>
            <% if session[:user_id] == 10 %>
              <small class='text-success'>Hello, <%= @current_user.email %></small>
              <li><%= link_to "Scarves", scarves_path %></li>
              <li><%= link_to "Products", "/products" %></li>
              <li><%= link_to "Orders", "#" %></li>
              <li><%= link_to "Account", account_path %></li>
              <li><%= link_to "Sign Out", log_out_path %></li>
            <% elsif @current_user %>
              <small class='text-success'>
                <div class ='success-email'>
                  Hello, <%= @current_user.email %>
                </div>
              </small>
              <li><%= link_to "Scarves", scarves_path %></li>
              <li><%= link_to "Cart (#{cart_total})", cart_path %></li>
              <li><%= link_to "My Account", account_path %></li>
              <li><%= link_to "Sign Out", log_out_path %></li>
            <% else %>
              <li><%= link_to "Scarves", scarves_path %></li>
              <li><%= link_to "Cart (#{cart_total})", cart_path %></li>
              <li><%= link_to "Sign Up", signup_path %></li>
            <% end %>
          </ul>
        </div>

        <% if !@current_user %>
          <div class="navbar-right">
            <%= form_tag log_in_path, class: "navbar-form" do %>
              <div class="form-group">
                <input type="email" name="email" placeholder="Email" class="form-control">
              </div>
              <div class="form-group">
                <input type="password" name="password" placeholder="Password" class="form-control">
              </div>
              <input type="submit" value="Log In" class="btn btn-default">
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>

<%= yield %>

</body>
</html>